### PR TITLE
Thermostat handling enhancement

### PR DESCRIPTION
**Pull request by siburny**
Purpose of this PR is to add "monitoring" thermostat mode. There was already a function to enable monitoring (though wrong group was used), but there was no mechanism to receive monitoring events. They are sent as direct commands (messageType = 0).

As part of testing I added more options to ./insteon-link script to help troubleshoot different linking issues.

### CODE REVIEW

**Comment by brandongoode** [comment]
Great work!  Thanks so much.

No wonder it never worked -- 0xEF not 0xFE -- duh! 

I finally gave up and assumed it was just one of the many Insteon features that didn't really work as advertised.

I would like to make a few modification to make the emited data match some of the other function and also add support for temp change events, `0x6E`.

- convert humidity to int
- setpoints and temp convert to temp using default units
- map mode to mode and fan 

Would you rather me make the changes? or since it's your PR would you like to do the update?  Either works for me.

Again - Thanks a bunch.

**Comment by siburny** [comment]
I will fix it. I didn't add 0x6E because my thermostat never sent in two days of testing :)

**Comment by siburny** [comment]
Before I commit I want to double check some things with you:

1. Convert all to int
I already do this before handleDirect is called. Command2 is converted to int. Should I not do this there and pass Command2 as is (hex) and then do all conversion in handleDirect in Thermostat class?

2. Convert temperature
Use something like this:
`convertTemp('F', insteon.defaultTempUnits, parseInt(data, 16)),`

3. Mode and fan:
Do similar what you are doing in status function? https://github.com/automategreen/home-controller/blob/ff0390aaea8f1c14750c9d466601b8b2d81ae284/lib/Insteon/Thermostat.js#L426

**Comment by brandongoode** [comment]
So the 0x6E is one of the doesn't work as advertised features.  Also reading the dev notes is states "To set a device to get status reporting add a controller of device link with group 0xEF and set 0x2E to 0x08."  The second part "set 0x2E to 0x08" may be required to get the temperatures to report.

On page 21:

  0x08 Data 2: 8 To check EF group and set the EF group flag in firmware
  [TX] - 02 62 1F 0E 3C 1F 2E 00 00 08 00 00 00 00 00 00 00 00 00 00 00 CA

Responses to questions:

  1. I missed the covert to int prior to calling the handler.  That works.
  2. Yes.  Use the `convertTemp` function. 
  3. See below

For the mode, what I have has deferent values.  Here's what I have from the therm dev notes, http://cache.insteon.com/developer/2441ZTHdev-112012-en.pdf

0x00 – Off Mode
0x01 – Heat Mode
0x02 – Cool Mode
0x03 – Auto Mode
0x04 – Program Mode
0x10 – Off Mode with Fan On
0x11 – Heat Mode with Fan On
0x12 – Cool Mode with Fan On
0x13 – Auto Mode with Fan On
0x14 – Program Mode with Fan On

I was thinking something like:

```js
  case '70':
    var fan = !!(cmd2 & 0x10);
    var modes = ['off', 'heat', 'cool', 'auto', 'program'];
    var mode = modes[cmd2 & 0x0F];
    this.emit('status', { 'mode': mode, 'fan': fan });
    break;
```

**Comment by siburny** [comment]
I was using the following doc: http://cache.insteon.com/developer/2441THdev-062012-en.pdf
It's for wired thermostat: for some reason it has different table, weird.

set 0x2E to 0x08: I saw that and did try it, but no temperature report came back. I think I should modify "monitor" function to include this anyway.

That snippet looks perfect, I will use it right now.

**Comment by siburny** [comment]
I've committed the changes. One thing I noticed is I was sending 0x2E (flag) command wrong in my tests - that might be a reason why I didn't receive any temperature events.

**Comment by brandongoode** [comment]
Thanks so much for all the work.  It's going to be a great addition.  (I wish Insteon would support it for the new Hubs via their API).  

I'll work to have this moved into my production servers over the next few week.  Once it been stable for a few days, I'll publish a new version on npm.

Again Thanks.

**Comment by siburny** [comment]
I am testing this locally in my house - hopefully will see all events in 24 hour period. Thanks!

**Comment by siburny** [comment]
So the good news is I did get temperature status event overnight, but for some reason it was only one event. Weird.

**Comment by brandongoode** [comment]
That's odd.  Do the temp in your house not change ;-) You must have good insulation. 

Another thought, the thermostat may only send the temp event when it doesn't coincide with a cooling (or heating) event.

**Pull request merged**
