### PR TITLE
Fix issue 49

### PR DESCRIPTION
**Pull request by siburny**

### CODE REVIEW

**Comment by brandongoode** [comment]
Thanks again -- and if you want to merge the fixes to bin you had in the original PR, that would be cool too.

**Comment by siburny** [comment]
They are there: I just "squashed" all commits in two main ones.

**Comment by siburny** [comment]
I will work on additional code coverage so I will send another PR soon

**Comment by brandongoode** [comment]
Cool.  I didn't relook at the changed files close enough.  Thanks.

**Comment by brandongoode** [comment]
@siburny What would you think of being a collaborator on this project?

**Comment by siburny** [comment]
@brandongoode that would be great!

**Comment by brandongoode** [comment]
@siburny Cool -- I could use the help.  You should have an invite.

**Pull request merged**
